"""payment table status update with enum

Revision ID: 40aad17952e1
Revises: 54b1f306f33f
Create Date: 2026-07-16 16:26:59.029592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40aad17952e1'
down_revision: Union[str, Sequence[str], None] = '54b1f306f33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PAID', 'FAILED', 'PENDING', 'REFUNDED', name='paymentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PAID', 'FAILED', 'PENDING', 'REFUNDED', name='paymentstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
