"""update otp table

Revision ID: 8b5a53c0564b
Revises: d6aee6d034dc
Create Date: 2026-07-09 07:02:05.273430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5a53c0564b'
down_revision: Union[str, Sequence[str], None] = 'd6aee6d034dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('otp_hash', sa.String(length=255), nullable=False))
    op.add_column('otp_codes', sa.Column('purpose', sa.String(length=30), nullable=False))
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), nullable=False))
    op.drop_column('otp_codes', 'otp')
    op.drop_column('otp_codes', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('otp_codes', sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('otp_codes', 'attempts')
    op.drop_column('otp_codes', 'purpose')
    op.drop_column('otp_codes', 'otp_hash')
    # ### end Alembic commands ###
