"""add report sync fields

Revision ID: d97abbc72d96
Revises: b98d92ba854e
Create Date: 2026-07-09 16:01:57.359069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97abbc72d96'
down_revision: Union[str, Sequence[str], None] = 'b98d92ba854e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('pdf_generated', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('email_sent', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('sync_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'sync_status')
    op.drop_column('reports', 'email_sent')
    op.drop_column('reports', 'pdf_generated')
    # ### end Alembic commands ###
