"""payment model modified

Revision ID: ddcbe3e9c4be
Revises: 2f78786ac383
Create Date: 2026-07-15 20:51:58.784470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcbe3e9c4be'
down_revision: Union[str, Sequence[str], None] = '2f78786ac383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_column('payments', 'stripe_payment_intent')
    # ### end Alembic commands ###
